Fixed more Leanpub line-wraps warnings
- We had to add line-wraps to some code shown below:
>irb

> require "selenium-webdriver"
=> true

> browser = Selenium::WebDriver.for :chrome
Selenium::WebDriver::Error::WebDriverError: Unable
to find the chromedriver executable. Please
download the server from
http://chromedriver.storage.googleapis.com/index.html
and place it somewhere on your PATH. More info at
http://code.google.com/p/selenium/wiki/ChromeDriver.
(...)

- We had to add line-wraps to some code shown below:
$ irb

> require "selenium-webdriver"
=> true

> browser = Selenium::WebDriver.for :chrome
Selenium::WebDriver::Error::WebDriverError: Unable
to find the chromedriver executable. Please
download the server from
http://code.google.com/p/chromedriver/downloads/list
and place it somewhere on your PATH. More info at
http://code.google.com/p/selenium/wiki/ChromeDriver.
(...)

- We had to add line-wraps to some code shown below:
$ irb

> require "selenium-webdriver"
=> true

> Selenium::WebDriver::Chrome.path =
"/Applications/Chromium.app/Contents/MacOS/Chromium"
=> "/Applications/Chromium.app/Contents/MacOS/Chromium"

> browser = Selenium::WebDriver.for :chrome
=> #<Selenium::WebDriver::Driver:
0x1e35d5faa9511ec6 browser=:chrome>

> browser.get "http://watir.com"
=> nil

- We had to add line-wraps to some code shown below:
$ ruby -v
The program 'ruby' can be found in the following packages:
 * ruby1.8
 * ruby1.9.1
Try: sudo apt-get install <selected package>

- We had to add line-wraps to some code shown below:
$ gem update --system
ERROR:  While executing gem ... (RuntimeError)
gem update --system is disabled on Debian, because it will overwrite the
content of the rubygems Debian package, and might break your Debian
system
in subtle ways. The Debian-supported way to update rubygems is through
apt-get, using Debian official repositories.
If you really know what you are doing, you can still update rubygems by
setting the REALLY_GEM_UPDATE_SYSTEM environment variable, but please
remember that this is comp

- We had to add line-wraps to some code shown below:
> browser.find_element(link_text: "Google.com").click
=> "ok"

- We had to add line-wraps to some code shown below:
> browser = Selenium::WebDriver.for :ff
=> #<Selenium::WebDriver::Driver:0x..faf203ad50b5b4c08 browser=:firefox>

- We had to add line-wraps to some code shown below:
> browser.find_element(name: "q")
=> #<Selenium::WebDriver::Element:0x2ab0c124c2d3bb12
   id="{25201324-ac0c-8e40-9766-c35aa5b54786}">

- We had to add line-wraps to some code shown below:
> browser["gbqfq"]
=> #<Selenium::WebDriver::Element:0x6faea7c65902853c
   id="{fca96529-8bc6-bf4f-8e78-376f037c351a}">

- We had to add line-wraps to some code shown below:
>  browser.find_element(name: "q").attribute(:name)
=> "q"

>  browser.find_element(name: "q").attribute(:class)
=> "lst tiah"

>  browser.find_element(name: "q").attribute(:type)
=> "text"

>  browser.find_element(name: "q").attribute(:autocomplete)
=> "off"

- We had to add line-wraps to some code shown below:
>  browser.find_element(name: "q").attribute(:outerHTML)
=> "<input autocomplete=\"off\" class=\"lst tiah\"
...

- We had to add line-wraps to some code shown below:
require "selenium-webdriver"
browser = Selenium::WebDriver.for :phantomjs
browser.get "http://google.com"
p browser.current_url
p browser.title
browser.find_element(name: "q").send_keys "watir"
browser.find_element(name: "q").clear
p browser.find_element(name: "q").attribute(:name)
p browser.find_element(name: "q").attribute(:class)
p browser.find_element(name: "q").attribute(:type)
p browser.find_element(name: "q").attribute(:autocomplete)
browser.save_screenshot "phantomjs.png"
p browser.page_s

- We had to add line-wraps to some code shown below:
﻿Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\IEUser>

- We had to add line-wraps to some code shown below:
﻿Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\IEUser>ruby file_name.rb