Fixed Leanpub line-wraps warnings
- We had to add line-wraps to some code shown below:
>ruby -v
'ruby' is not recognized as an internal or external command,
operable program or batch file.

- We had to add line-wraps to some code shown below:
>irb

> require "selenium-webdriver"
=> true

> browser = Selenium::WebDriver.for :internet_explorer
Selenium::WebDriver::Error::WebDriverError: Unable to find standalone
executable. Please download the IEDriverServer from
http://code.google.com/p/selenium/downloads/list and place the
executable on
your PATH.
(...)

- We had to add line-wraps to some code shown below:
>PATH
PATH=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;
C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Ruby200\bin

- We had to add line-wraps to some code shown below:
>irb

> require "selenium-webdriver"
=> true

> browser = Selenium::WebDriver.for :internet_explorer
Started InternetExplorerDriver server (32-bit)
2.38.0.0
Listening on port 5555
=> #<Selenium::WebDriver::Driver:0x5469141e browser=:internet_explorer>

> browser.get "http://watir.com"
=> nil

- We had to add line-wraps to some code shown below:
>irb

> require "selenium-webdriver"
=> true

> browser = Selenium::WebDriver.for :firefox
=> #<Selenium::WebDriver::Driver:0xdc8ad4a browser=:firefox>

> browser.get "http://watir.com"
=> ""

- We had to add line-wraps to some code shown below:
>irb

> require "selenium-webdriver"
=> true

> browser = Selenium::WebDriver.for :chrome
Selenium::WebDriver::Error::WebDriverError: Unable to find the
chromedriver
executable. Please download the server
from http://chromedriver.storage.googleapis.com/index.html and place it
somewhere on your PATH. More info at
http://code.google.com/p/selenium/wiki/ChromeDriver.
(...)

- We had to add line-wraps to some code shown below:
>irb

> require "selenium-webdriver"
=> true

> browser = Selenium::WebDriver.for :chrome
Starting ChromeDriver (v2.7.236900) on port 9515
=> #<Selenium::WebDriver::Driver:0x..fc23f2ebe browser=:chrome>

> browser.get "http://watir.com"
=> nil

- We had to add line-wraps to some code shown below:
>irb

> require "selenium-webdriver"
=> true

> Selenium::WebDriver::Chrome.path = 'C:\chrome\chrome.exe'
=> "C:\\chrome\\chrome.exe"

> browser = Selenium::WebDriver.for :chrome
Starting ChromeDriver (v2.7.236900) on port 9515
=> #<Selenium::WebDriver::Driver:0x..f9d38b82e browser=:chrome>

> browser.get "http://watir.com"
=> nil

- We had to add line-wraps to some code shown below:
>irb

> browser = Selenium::WebDriver.for :phantomjs
(...)
=> #<Selenium::WebDriver::Driver:0x442ed372 browser=:phantomjs>

> browser.get "http://watir.com"
=> {}

> browser.save_screenshot "phantomjs.png"
=> #<File:phantomjs.png (closed)>

- We had to add line-wraps to some code shown below:
>java -version
'java' is not recognized as an internal or external command,
operable program or batch file.

- We had to add line-wraps to some code shown below:
>java -version
java version "1.7.0_45"
Java(TM) SE Runtime Environment (build 1.7.0_45-b18)
Java HotSpot(TM) Client VM (build 24.45-b08, mixed mode, sharing)

- We had to add line-wraps to some code shown below:
>irb

> require "selenium-webdriver"
=> true

> browser = Selenium::WebDriver.for :opera
Selenium::WebDriver::Error::WebDriverError: Unable to find the Selenium
server jar.  Please download the standalone server from
http://code.google.com/p/selenium/downloads/list and set the
SELENIUM_SERVER_JAR environmental variable to its location.  More info
at
http://code.google.com/p/selenium/wiki/OperaDriver.
(...)

- We had to add line-wraps to some code shown below:
>set
SELENIUM_SERVER_JAR=C:\Ruby200\bin\selenium-server-standalone-2.39.0.jar

- We had to add line-wraps to some code shown below:
>irb

> require "selenium-webdriver"
=> true

> browser = Selenium::WebDriver.for :opera
Selenium::WebDriver::Error::UnknownError: Could not find a platform that
supports bundled launchers, please set it manually
Build info: version: '2.39.0', revision: 'ff23eac',
time: '2013-12-16 16:11:15'
System info: host: 'IE11WIN8_1', ip: '10.0.2.15', os.name: 'Windows 8',
os.arch: 'x86', os.version: '6.2', java.version: '1.7.0_45'
Driver info: driver.version: OperaDriver
(org.openqa.selenium.WebDriverExcep

- We had to add line-wraps to some code shown below:
>setx SELENIUM_SERVER_JAR
C:\Ruby200\bin\selenium-server-standalone-2.39.0.jar
SUCCESS: Specified value was saved.

- We had to add line-wraps to some code shown below:
$ ruby -v
ruby 2.0.0p247 (2013-06-27 revision 41674) [universal.x86_64-darwin13]

- We had to add line-wraps to some code shown below:
$ sudo gem install selenium-webdriver
(...)
Fetching: ffi-1.9.3.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing selenium-webdriver:
ERROR: Failed to build gem native extension.
(...)

- We had to add line-wraps to some code shown below:
$ sudo gem install selenium-webdriver --no-ri --no-rdoc
(...)
Successfully installed selenium-webdriver-2.37.0
(...)

- We had to add line-wraps to some code shown below:
$ irb

> require "selenium-webdriver"
=> true

> browser = Selenium::WebDriver.for :safari
=> #<Selenium::WebDriver::Driver:0x..f93d5546968bec45e browser=:safari>

> browser.get "http://watir.com"
=> nil

- We had to add line-wraps to some code shown below:
$ irb

> require "selenium-webdriver"
=> true

> browser = Selenium::WebDriver.for :firefox
=> #<Selenium::WebDriver::Driver:0x10e1416dd9107ffe browser=:firefox>

> browser.get "http://watir.com"
=> ""

- We had to add line-wraps to some code shown below:
$ ruby -e "$(curl -fsSL
https://raw.github.com/mxcl/homebrew/go/install)"
(...)
==> Installation successful!
You should run `brew doctor' *before* you install anything.
Now type: brew help

- We had to add line-wraps to some code shown below:
$ irb

> require "selenium-webdriver"
=> true

> browser = Selenium::WebDriver.for :chrome
Selenium::WebDriver::Error::WebDriverError: Unable to find the
chromedriver
executable. Please download the server from
http://code.google.com/p/chromedriver/downloads/list and place it
somewhere
on your PATH. More info at
http://code.google.com/p/selenium/wiki/ChromeDriver.
(...)

- We had to add line-wraps to some code shown below:
$ irb

> require "selenium-webdriver"
=> true

> browser = Selenium::WebDriver.for :chrome
=> #<Selenium::WebDriver::Driver:0xec6568f803e9898 browser=:chrome>

> browser.get "http://watir.com"
=> ""

- We had to add line-wraps to some code shown below:
$ irb

> require "selenium-webdriver"
=> true

> Selenium::WebDriver::Chrome.path =
"/Applications/Chromium.app/Contents/MacOS/Chromium"
=> "/Applications/Chromium.app/Contents/MacOS/Chromium"

> browser = Selenium::WebDriver.for :chrome
=> #<Selenium::WebDriver::Driver:0x1e35d5faa9511ec6 browser=:chrome>

> browser.get "http://watir.com"
=> nil

- We had to add line-wraps to some code shown below:
$ irb

> require "selenium-webdriver"
=> true

> browser = Selenium::WebDriver.for :phantomjs
=> #<Selenium::WebDriver::Driver:0x..fbdc736b89bb162d0
browser=:phantomjs>

> browser.get "http://watir.com"
=> ""

> browser.save_screenshot "phantomjs.png"
=> #<File:phantomjs.png (closed)>

- We had to add line-wraps to some code shown below:
$ irb

> require "selenium-webdriver"
=> true

> browser = Selenium::WebDriver.for :opera
Selenium::WebDriver::Error::WebDriverError: Unable to find the Selenium
server jar.  Please download the standalone server from
http://code.google.com/p/selenium/downloads/list and set the
SELENIUM_SERVER_JAR environmental variable to its location. More info at
http://code.google.com/p/selenium/wiki/OperaDriver.
(...)

- We had to add line-wraps to some code shown below:
$ java -version
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-462-11M4609)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-462, mixed mode)

- We had to add line-wraps to some code shown below:
$ export SELENIUM_SERVER_JAR=
/usr/local/opt/selenium-server-standalone/selenium-server-standalone-2.3
7.0.jar

- We had to add line-wraps to some code shown below:
$ irb

> require "selenium-webdriver"
=> true

> browser = Selenium::WebDriver.for :opera
Selenium::WebDriver::Error::UnknownError: Invalid service list received:
(...)
(java.lang.IllegalStateException)
(...)

- We had to add line-wraps to some code shown below:
$ irb

> require "selenium-webdriver"
=> true

> browser = Selenium::WebDriver.for :opera
=> #<Selenium::WebDriver::Driver:0x..fc28c93dae7536a48 browser=:opera>

> browser.get "http://watir.com"
 => nil

- We had to add line-wraps to some code shown below:
$ cat ~/.bash_profile
export SELENIUM_SERVER_JAR=
/usr/local/opt/selenium-server-standalone/selenium-server-standalone-2.3
7.0.jar

- We had to add line-wraps to some code shown below:
$ ruby -v
The program 'ruby' can be found in the following packages:
 * ruby1.8
 * ruby1.9.1
Try: sudo apt-get install <selected package>

- We had to add line-wraps to some code shown below:
$ ruby -v
ruby 1.9.3p194 (2012-04-20 revision 35410) [i686-linux]

- We had to add line-wraps to some code shown below:
$ gem update --system
ERROR:  While executing gem ... (RuntimeError)
gem update --system is disabled on Debian, because it will overwrite the
content of the rubygems Debian package, and might break your Debian
system
in subtle ways. The Debian-supported way to update rubygems is through
apt-get, using Debian official repositories.
If you really know what you are doing, you can still update rubygems by
setting the REALLY_GEM_UPDATE_SYSTEM environment variable, but please
remember that this is comp

- We had to add line-wraps to some code shown below:
$ sudo gem install selenium-webdriver --no-ri --no-rdoc
(...)
Fetching: ffi-1.9.3.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing selenium-webdriver:
ERROR: Failed to build gem native extension.
(...)

- We had to add line-wraps to some code shown below:
$ sudo apt-get install ruby1.9.1-dev
(...)
Setting up ruby1.9.1-dev (1.9.3.194-8.1ubuntu2.1) ...

- We had to add line-wraps to some code shown below:
$ irb

> require "selenium-webdriver"
=> true

> browser = Selenium::WebDriver.for :firefox
=> #<Selenium::WebDriver::Driver:0x21564606 browser=:firefox>

> browser.get "http://watir.com"
=> ""

- We had to add line-wraps to some code shown below:
$ irb

> require "selenium-webdriver"
=> true

> browser = Selenium::WebDriver.for :phantomjs
=> #<Selenium::WebDriver::Driver:0x..fa5f26f44 browser=:phantomjs>

> browser.get "http://watir.com"
=> {}

> browser.save_screenshot "phantomjs.png"
=> #<File:phantomjs.png (closed)>

- We had to add line-wraps to some code shown below:
$ echo $PATH
/home/zeljko/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:
/sbin:/bin:/usr/games

- We had to add line-wraps to some code shown below:
$ irb

> require "selenium-webdriver"
=> true

> browser = Selenium::WebDriver.for :chrome
=> #<Selenium::WebDriver::Driver:0x5b77effe browser=:chrome>

> browser.get "http://watir.com"
=> nil

- We had to add line-wraps to some code shown below:
$ sudo apt-get install chromium-browser
(...)
Setting up chromium-browser (30.0.1599.114-0ubuntu0.13.10.2) ...
(...)

- We had to add line-wraps to some code shown below:
$ irb

> require "selenium-webdriver"
=> true

> Selenium::WebDriver::Chrome.path = "/usr/bin/chromium-browser"
=> "/usr/bin/chromium-browser"

> browser = Selenium::WebDriver.for :chrome
=> #<Selenium::WebDriver::Driver:0x..fb4c9860a browser=:chrome>

> browser.get "http://watir.com"
=> nil

- We had to add line-wraps to some code shown below:
$ java -version
The program 'java' can be found in the following packages:
 * default-jre
 * gcj-4.6-jre-headless
 * gcj-4.7-jre-headless
 * openjdk-7-jre-headless
 * openjdk-6-jre-headless
Try: sudo apt-get install <selected package>

- We had to add line-wraps to some code shown below:
$ sudo apt-get install openjdk-7-jre-headless
(...)
Setting up openjdk-7-jre-lib (7u25-2.3.12-4ubuntu3) ...
(...)

- We had to add line-wraps to some code shown below:
$ export
SELENIUM_SERVER_JAR=~/Downloads/selenium-server-standalone-2.39.0.jar

- We had to add line-wraps to some code shown below:
$ irb

> require "selenium-webdriver"
=> true

> browser = Selenium::WebDriver.for :opera
=> #<Selenium::WebDriver::Driver:0x..fb4bb92ce browser=:opera>

> browser.get "http://watir.com"
=> nil

- We had to add line-wraps to some code shown below:
$ printenv | grep SELENIUM
SELENIUM_SERVER_JAR=/home/zeljko/bin/selenium-server-standalone-2.39.0.j
ar

- We had to add line-wraps to some code shown below:
> browser = Selenium::WebDriver.for :firefox
=> #<Selenium::WebDriver::Driver:0x10e1416dd9107ffe browser=:firefox>

- We had to add line-wraps to some code shown below:
> browser.current_url
=> "https://www.google.hr/?gws_rd=cr&ei=RDrkUrWVJOS24ASbyYCQDQ"

- We had to add line-wraps to some code shown below:
> browser.find_element(link_text: "Google.com").click
=> "ok"

- We had to add line-wraps to some code shown below:
$ ruby quick_start.rb
https://www.google.hr/?gws_rd=cr&ei=RkLkUvqMIYeH4gTf_oDYBQ
Google Images
126

- We had to add line-wraps to some code shown below:
$ irb

> require "selenium-webdriver"
 => true

> browser = Selenium::WebDriver.for :firefox
=> #<Selenium::WebDriver::Driver:0x..f8698791d2bff9778 browser=:firefox>

- We had to add line-wraps to some code shown below:
> browser = Selenium::WebDriver.for :ff
=> #<Selenium::WebDriver::Driver:0x..faf203ad50b5b4c08 browser=:firefox>

- We had to add line-wraps to some code shown below:
> browser.current_url
=> "https://www.google.hr/?gws_rd=cr&ei=xXjtUr6oAqTL4wTvooCYDQ"

- We had to add line-wraps to some code shown below:
$ ruby driver.rb
"https://www.google.hr/?gfe_rd=ctrl&ei=6QEOU4P4AYeV_Aaj_4CQDA&gws_rd=cr"
"Google"

- We had to add line-wraps to some code shown below:
$ irb

> require "selenium-webdriver"
 => true

> browser = Selenium::WebDriver.for :firefox
=> #<Selenium::WebDriver::Driver:0x..f8698791d2bff9778 browser=:firefox>

> browser.get "http://google.com"
=> ""

- We had to add line-wraps to some code shown below:
> browser.find_element(name: "q")
=> #<Selenium::WebDriver::Element:0x2ab0c124c2d3bb12
   id="{25201324-ac0c-8e40-9766-c35aa5b54786}">

- We had to add line-wraps to some code shown below:
> browser["gbqfq"]
=> #<Selenium::WebDriver::Element:0x6faea7c65902853c
   id="{fca96529-8bc6-bf4f-8e78-376f037c351a}">

- We had to add line-wraps to some code shown below:
> browser["gbqfq"].attribute(:name)
=> "q"

> browser["gbqfq"].attribute(:class)
=> "gbqfif"

> browser["gbqfq"].attribute(:type)
=> "text"

> browser["gbqfq"].attribute(:autocomplete)
=> "off"

> browser["gbqfq"].attribute(:style)
=> "border: medium none; padding: 0px; margin: 0px; height: auto;
width: 100%;
background: url(\"data:image/gif;base64,R0lGODlhAQABAID/
AMDAwAAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw%3D%3D\") repeat scroll 0% 0%
transparent; position: absolute; z-index: 6; left: 0px; outli

- We had to add line-wraps to some code shown below:
$ ruby element.rb
"q"
"gbqfif"
"text"
"off"
"border: medium none; padding: 0px; margin: 0px; height: auto; width:
100%; ...
"<input spellcheck=\"false\" dir=\"ltr\" style=\"border: medium none;
...

- We had to add line-wraps to some code shown below:
$ irb

> require "selenium-webdriver"
 => true

> browser = Selenium::WebDriver.for :phantomjs
=> #<Selenium::WebDriver::Driver:0x4a9629199067c7c6 browser=:phantomjs>

- We had to add line-wraps to some code shown below:
> browser.current_url
=> "http://www.google.hr/?gfe_rd=cr&ei=LJwMU_nuAsHe_Aa50IHIAQ"

> browser.title
=> "Google"

- We had to add line-wraps to some code shown below:
>  browser.find_element(name: "q").attribute(:name)
=> "q"

>  browser.find_element(name: "q").attribute(:class)
=> "lst tiah"

>  browser.find_element(name: "q").attribute(:type)
=> "text"

>  browser.find_element(name: "q").attribute(:autocomplete)
=> "off"

- We had to add line-wraps to some code shown below:
> browser.page_source
=> "<!DOCTYPE html><html itemscope=\"\"
itemtype=\"http://schema.org/WebPage\">
<head><meta itemprop=\"image\"
content=\"/images/google_favicon_128.png\">
<title>Google</title><script>
...
</script></body></html>"

- We had to add line-wraps to some code shown below:
>  browser.find_element(name: "q").attribute(:outerHTML)
=> "<input autocomplete=\"off\" class=\"lst tiah\" value=\"\"
title=\"Google pretraživanje\" maxlength=\"2048\" name=\"q\" size=\"57\"
style=\"color: rgb(0, 0, 0); margin-top: 0px; margin-right: 0px;
margin-bottom:
 0px; margin-left: 0px; padding-top: 5px; padding-bottom: 0px;
 padding-left: 6px; vertical-align: top; padding-right: 38px;
 outline-style: none; outline-width: initial; outline-color: initial; \"
 dir=\"ltr\" spellcheck=\"false

- We had to add line-wraps to some code shown below:
require "selenium-webdriver"
browser = Selenium::WebDriver.for :phantomjs
browser.get "http://google.com"
p browser.current_url
p browser.title
browser.find_element(name: "q").send_keys "watir"
browser.find_element(name: "q").clear
p browser.find_element(name: "q").attribute(:name)
p browser.find_element(name: "q").attribute(:class)
p browser.find_element(name: "q").attribute(:type)
p browser.find_element(name: "q").attribute(:autocomplete)
browser.save_screenshot "phantomjs.png"
p browser.page_s

- We had to add line-wraps to some code shown below:
$ ruby headless_phantomjs.rb
"http://www.google.hr/?gfe_rd=ctrl&ei=7wUOU72wMMWB_AaEzoCgAQ&gws_rd=cr"
"Google"
"q"
"lst tiah"
"text"
"off"
"<!DOCTYPE html><html itemscope=\"\"
itemtype=\"http://schema.org/WebPage\">...
"<input autocomplete=\"off\" class=\"lst tiah\" value=\"\"
title=\"Google ...

- We had to add line-wraps to some code shown below:
﻿$ irb

> require "headless"
=> true

> require "selenium-webdriver"
=> true

﻿> headless = Headless.new
=> #<Headless:0x9e957d8 @display=99, @autopick_display=true,
@reuse_display=true, @dimensions="1280x1024x24",
@video_capture_options={},
@destroy_at_exit=true>

> headless.start
=>
#<Proc:0x9eaa2b4@/home/z/.rvm/gems/ruby-2.1.1/gems/headless-1.0.1/lib/
headless.rb:175>

> browser = Selenium::WebDriver.for :firefox
=> #<Selenium::WebDriver::Driver:0x..f9de848e2 browser=:firefox>

> browser.get "

- We had to add line-wraps to some code shown below:
$ ls
Book.txt	Gemfile.lock	README.md	VERSION		images		lib		misc
Gemfile		LICENSE.md	Subset.txt	epub_images	installation	main		old

- We had to add line-wraps to some code shown below:
> doge
NameError: undefined local variable or method `doge' for main:Object
from (irb):7
from /Users/z/.rvm/rubies/ruby-2.1.1/bin/irb:11:in `<main>'

- We had to add line-wraps to some code shown below:
> pp doge
NoMethodError: undefined method `pp' for main:Object
from (irb):9
from /Users/z/.rvm/rubies/ruby-2.1.1/bin/irb:11:in `<main>'

- We had to add line-wraps to some code shown below:
> pp doge
{:dogecoin=>"To the moon!",
:hello=>"This is Doge",
:wow=>"much addon",
:so=>"internet"}
=> {:dogecoin=>"To the moon!", :hello=>"This is Doge", :wow=>"much
addon", :so=>"internet"}

- We had to add line-wraps to some code shown below:
$ ruby -v
The program 'ruby' can be found in the following packages:
* ruby1.8
* ruby1.9.1

- We had to add line-wraps to some code shown below:
$ ruby -v
ruby 2.1.1p76 (2014-02-24 revision 45161) [i686-linux]

- We had to add line-wraps to some code shown below:
$ rvm list

rvm rubies

   ruby-2.1.0 [ i686 ]
=> ruby-2.1.1 [ i686 ]

# Default ruby not set. Try 'rvm alias create default <ruby>'.

# => - current
# =* - current && default
#  * - default

- We had to add line-wraps to some code shown below:
﻿Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\IEUser>

- We had to add line-wraps to some code shown below:
﻿Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\IEUser>ruby file_name.rb